title: Three Key Therapy - Brand 
description: Assets contributing to the brand
theme: just-the-docs

url: https://threekeytherapy.github.io/brand/


# Aux links for the upper right navigation
aux_links:
  "Back to main website":
    - "https://www.threekeytherapy.com"
  "This site on GitHub":
    - "https://github.com/threekeytherapy/brand"


# Enable or disable heading anchors
heading_anchors: true

# Footer content
# appears at the bottom of every page's main content

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

footer_content: "Copyright &copy; Three Key Therapy"

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/threekeytherapy/brand" # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from

color_scheme: threekeytherapy
favicon_ico: "/assets/images/favicon-mahogony.png"
logo: "/assets/images/SVG_RGB_WebsiteUse_ThreeKeyTherapy_Logo_Horizontal_Mahogony.svg"
